default_parameters = {
    'sheet_name': 0,
    'residues': None,
    'distance': None,
    'linker': None,
    'source': None,
    'unit': 'nm',
    'speed': None,
    'residues_distance': 0.365,
    'minimal_stretch_distance': 10,
    'plot_columns': 4,
    'separator': ',',
    'states': None,
    'high_force_cutoff': {None: 1, 'theory': 1, 'experiment': 5},
    'low_force_cutoff': {None: 0.1, 'theory': 0.1, 'experiment': 5},
    'max_rupture_force': {None: 25, 'theory': 25, 'experiment': 42},
    'initial_guess': {None: {'p_prot': 0.7, 'p_dna': 0.1, 'k_prot': 0.005, 'k_dna': 0.005, 'l_dna': 345},
                      'theory': {'p_prot': 0.7, 'p_dna': 0.1, 'k_prot': 0.005, 'k_dna': 0.005, 'l_dna': 345},
                      'experiment': {'p_prot': 5.88, 'p_dna': 0.16, 'k_prot': 0, 'k_dna': 0.005, 'l_dna': 345}}
}